binop_separator = "Back"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "SameLineWhere"
color = "Auto"
combine_control_expr = true
comment_width = 80
condense_wildcard_suffixes = true
control_brace_style = "AlwaysSameLine"
disable_all_formatting = false
edition = "2021"
emit_mode = "Files"
empty_item_single_line = true
enum_discrim_align_threshold = 0
error_on_line_overflow = false
error_on_unformatted = false
fn_params_layout = "Vertical"
fn_single_line = false
force_explicit_abi = true
force_multiline_blocks = true
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = false
format_strings = false
hard_tabs = false
hide_parse_errors = false
ignore = []
imports_indent = "Block"
imports_layout = "Vertical"
indent_style = "Block"
inline_attribute_width = 0
make_backup = false
match_arm_blocks = true
match_block_trailing_comma = false
max_width = 80
merge_derives = true
imports_granularity = "Module"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
skip_children = false
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
struct_field_align_threshold = 20
struct_lit_single_line = false
tab_spaces = 2
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
unstable_features = true
use_field_init_shorthand = true
use_small_heuristics = "Off"
use_try_shorthand = false
version = "Two"
where_single_line = false
wrap_comments = true
fn_call_width = 20
attr_fn_like_width = 60
struct_lit_width = 20
struct_variant_width = 40
array_width = 60
chain_width = 10
single_line_if_else_max_width = 40
single_line_let_else_max_width = 40
